# Generated by Django 4.1 on 2024-08-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField(auto_now_add=True)),
                ('data_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data wystawienia faktury')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Łączna kwota', max_digits=10)),
                ('type', models.CharField(choices=[(1, 'przychod'), (2, 'wydatek')], help_text='Typ (Koszt/Przychód)', max_length=20)),
                ('invoice_number', models.CharField(help_text='Numer faktury', max_length=50)),
                ('category', models.CharField(choices=[(1, 'wystawienie kur'), (2, 'pasza'), (3, 'woda'), (4, 'prąd'), (5, 'leki'), (6, 'weterynaz'), (7, 'utylizacja'), (8, 'gaz'), (9, 'dezynfekcja'), (10, 'ubezpieczenie budynków')], help_text='Kategoria', max_length=20)),
                ('amount', models.IntegerField(default=None, help_text='Ilość', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=None, help_text='Cena jednostkowa', max_digits=10, null=True)),
                ('water_usage', models.DecimalField(decimal_places=2, default=None, help_text='Zużycie wody', max_digits=10, null=True)),
                ('forage_type', models.CharField(choices=[(1, 'przychod'), (2, 'wydatek')], help_text='Typ paszy', max_length=20)),
                ('payment_deadline', models.DateField(help_text='Termin zapłaty')),
                ('flock', models.ForeignKey(help_text='Rzut', on_delete=django.db.models.deletion.CASCADE, to='finance_monitor.flock')),
            ],
        ),
    ]
