# Generated by Django 4.1 on 2024-08-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='drug_name',
            field=models.CharField(help_text='Nazwa leku', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='forage_type',
            field=models.CharField(choices=[(1, 'starter'), (2, 'growler'), (3, 'finisher')], help_text='Typ paszy', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_deadline',
            field=models.DateField(help_text='Termin zapłaty', null=True),
        ),
    ]
