# Generated by Django 4.1 on 2024-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_monitor', '0002_invoice_drug_name_alter_invoice_forage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flock',
            name='data_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.IntegerField(choices=[(1, 'wystawienie kur'), (2, 'pasza'), (3, 'woda'), (4, 'prąd'), (5, 'leki'), (6, 'weterynaz'), (7, 'utylizacja'), (8, 'gaz'), (9, 'dezynfekcja'), (10, 'ubezpieczenie budynków')], help_text='Kategoria'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='forage_type',
            field=models.IntegerField(choices=[(1, 'starter'), (2, 'growler'), (3, 'finisher')], help_text='Typ paszy', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.IntegerField(choices=[(1, 'przychod'), (2, 'wydatek')], help_text='Typ (Koszt/Przychód)'),
        ),
    ]
